### PR TITLE
WL-3444 : adding dependency management for portal impl

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by buckett** [comment]
Why are we adding this if it isn't needed anywhere?

**Comment by nicholaswilson100** [comment]
FeedbackTool (feedback) has a reference to SkinnableCharonPortal (portal impl)

**Comment by nicholaswilson100** [comment]
This relates to WL-3444 in master, portal, kernel , feedback

**Comment by buckett** [comment]
Nothing outside the pack should ever depend on a impl. As an example the only thing that should ever depend on portal-impl is portal-pack.

**Pull request closed without merging**
